config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/work'
  get 'pages/service'
  get 'pages/bio'
  get 'pages/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
    #GET /articles
    def home
        @articles = article.all
    end

    #GET /articles/:id
    def show
        @article = Articles.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def work
  end

  def service
  end

  def bio
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
    <body>
      <header>
        <nav class="be-red white large-padding">
          <ul class="no-list row center-xs middle-xs">
            <ul class="col-md">
            <%= link_to "Home", root_path %> 
            </ul>
            <ul class="col-md">
            <%= link_to "Bio", pages_bio_path %>
            </ul>
            <ul class="col-md">
            <%= link_to "Servicios", pages_service_path %>
            </ul>
            <ul class="col-md">
            <%= link_to "Works", pages_work_path %>
            </ul>
            <ul class="col-md">
            <%= link_to "Contact", pages_new_path %>
            </ul>
          </ul>
        </nav>
      </header>
  
    <%= yield %>
    


    </body>
</html>

app/views/pages/bio.html.erb
<h1>| Bio |</h1>
<p>Find me in app/views/pages/bio.html.erb</p>

app/views/pages/home.html.erb
<h1>| Full stack developer | Web design | UX/UI |</h1>
<p></p>

app/views/pages/new.html.erb
<h1>| Conversemos |</h1>
<body>
    <section class="form-register">
    <h4>Deja tus datos y comentario</h4>
        <input class="controls" type="text" name="nombres" id="nombres" placeholder="Ingrese su Nombre">
        <input class="controls" type="text" name="apellidos" id="nombres" placeholder="Ingrese su apellido">
        <input class="controls" type="email" name="correo" id="correo" placeholder="Ingrese su correo">
        <input class="coment" type="text" name="comentario" id="correo" placeholder="Ingrese su comentario">
        <input class="buttons" type="submit" value="Dejar comentario">
        <p><a href="#"¿Ya tengo Cuenta?></a></p>
    </section>

</body>

app/views/pages/service.html.erb
<h1>| Servicios |</h1>
<p>Find me in app/views/pages/service.html.erb</p>

app/views/pages/work.html.erb
<h1>| Works |</h1>
<p>Find me in app/views/pages/work.html.erb</p>